#!/usr/bin/env node
var fs = require('fs')

var form = JSON.parse(fs.readFileSync(process.argv[2] || '/dev/stdin'))

var directions = process.argv[3]
  ? JSON.parse(fs.readFileSync(process.argv[3]))
  : {}

console.log(require('./')(form, directions))
